# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: golang:1.15

    working_directory: /go/src/github.com/ep4eg/babbler
    steps:
      - checkout
      - run:
          name: Building app
          command: CGO_ENABLED=0 go build -o babbler ./cmd/babbler/
      - store_artifacts:
          path: /go/src/github.com/ep4eg/babbler/babbler
          destination: babbler
  release:
    docker:
      - image: docker:19.03
    working_directory: /go/src/github.com/ep4eg/babbler
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Building image
          command: |
                  TAG=0.1.$CIRCLE_BUILD_NUM
                  docker build -t ep4eg/babbler:$TAG .
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  docker push ep4eg/babbler:$
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release
